language: node_js
node_js:
- '10'
script:
- gulp build
- gulp npmDist
deploy:
  matrix:
  - provider: pages
    local_dir: dist-site/
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    on:
      branch: master
  - provider: npm
    email: kim@shiftcph.dk
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
  api_key:
    secure: mqVvrieuuJLj9ix7gI9xDXCaVPUPLx/FfLBTlWqPWxTsS2twnkLipWbswxwv4eiLcldQFEMNzKoHCXjl2BftGKez5+OR3p7dm1Q8idOTiKJ63mzo7dPERljAQA1lWUdFZ3MAZnjrPGrj5FOgk+noASctNG4nNo1AJMpYvex099yZZkfw4PFjea6G6P07HtHo0XIK1ep5t2ZX+y9dQ1QO+ElF67U/on94LEuCU5PVJ2o8U5j0TOcfxe9ly2xdd+1diQi475RbadnMPUeyS7QM/MSYntILcDNZyzFoLLEi1pFMjsJqlQkBGvKd/t1jGrF4MrkeKS5kUre/PFHrToGiCIOnt5bKnmBqf11CM7tWlc5dWOi6BQXUSi03RGY9LZihtYE/UDIPZvS3jxtRavupgEvhuA0BCpcGMAnZ4G2589eza6QTQlQ8KpMNtJXoOrPOPuyG1h02x0Bs08hAAYo7D6q3rs4PCuUIvkH+9HMyzwmPj1ZDpbzGCT42DZaxjipWPWDtS3mpfUowBjxnX6h7FulMtSGSG7p/piQGPcX0xo4yEGR//FUxrtHnVvQw16OlOavzI87rIPYBo127KDBR3AsZUpKmnZRrNQu01Ztz8OcHozrE28jCFk+FFJpHVsoMXa0GzvxXVqQ+lha+3/k+FbR0v3AmJKuJDplbMClMUFY=
