language: node_js
node_js:
  - '10'
script:
  - gulp build
  - gulp npmDist
deploy:
  - provider: pages
    local_dir: dist-site/
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: npm
    email: kim@shiftcph.dk
    api_key:
      secure: Iyes5nBJq7U/zj/uNEJpelmlur619VQTZnZ1gTye99EFsm3lwGck6H3Q6ls29dqh3kycm3gOfy7bft1FQsV/STsgGEGQ+4i/6Pg/NUcmloKIpimzEacjK25B1JSyH2+rBdp/CI21IAmoQjaW/ePMcGkVsr6CEAfPsV9Ncmp2f7glCjHQ16GltILWNGvx58vYxzPbuImn7NXpw6l55Kq9TRMhqiTLidZUQbW70fyBdHoCyboj8TnzlgzRor78rR2RR4lFPIXDZ6kuUn1DNgxcGab/yuj4I5+rRto5c8Co3HBFtMIsLSe8kDRonJxhxhcBsbDUJsKuM4BfhOVzOa3Sw2MAUR06znzwocZBd6rMhGq5WQCdj5yPwnMbYiNe/rsAkXQJ51RM4RInqNjqn8Cjpie1PlstkvxFJKESXR+Rh1YpCJG3O9eIJI68jOTGrZ6VPdcFMbsHmndm6HU6AeL7CSI+M5NHsASYHJ1utR/AyMLET1PSGLCXAg5FHA4jFvBZssE1JUyX1dYmi2s/SSLd7+H/NJ5Stk6VJOm1DA7dxtx5pjE+QhBn0oBfTmuz/Qs04n7jRi+SLRpSRopN/XWeojeuoTRlfv6i+TSW5VsAYxghrcN+Vx5LxCDHn8cAZWaS4U20LHdqQLXRYf/y/NvFVUPv5++T1C9KuXelcJrjRMU=
    on:
      tags: true
      all_branches: true
