language: node_js
node_js:
  - '10'
script:
  - gulp build
  - gulp npmDist
deploy:
  - provider: pages
    local_dir: dist-site/
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: npm
    email: kim@shiftcph.dk
    api_key:
      secure: "Q499TanxngEY+g261KOTkbAYBIjdQDPcuntGaOTbVDoYdiOIiOcgXUI3F38aRCHO+xoOhlUqwvMZF7alihp/2hovhInTg36MN2ufLg6fiEPGfnac1ODgTriRvU8HXvDH3gALqzW+Mxnqqc0aH1Gd4NT/QLS7JQA3agRy5NQT/3PeEnwFaG5GqTEfio+H9IR2QJwJBW5cVjxOKEV3lxi/MWnSgXIuz/1ziB8dj0d/9hqNasamh1c6Gbm3bFy4Y3VXTI9if8sjKLywZXFsL37VbECKqNQoGlYI/WnlcURp1PXZ/AfpRmv1YAfv6bHkqRCUgfgYLK3jEHijL3hK5yUWsvQ8lD/eqDmSuGmQJ6nL8wG/N/+N1R7hEzluFUkTHkOb0pSJm83EVoLfw778L4DqGRgfuCh1ORLX/MTbWT9D2iGjbZlZmPgYO1JulWvb52/FiuIUd7tuVcqDg9Fn0vFKJS39RJXexHMhWT7MleAkKX5eyX2staQU6Egsw5gABzuLFMOOhTMQ8AIxOBqfApSpcjbhU2nrISXBGjNjhGHmZYyLvB8wUT1YPKMCxUWA0BMR490+nN1goDAJWADIoLcskSicoNuiaSWQHFUZn9BFfKsfQLsO3lfu9ONjB/K3ywzUQgudrQTQHpispyvQj4JkyquKjH5bjgHVWmeQ+Sq5Sfo="
    on:
      tags: true
