language: node_js
node_js:
  - '10'
script:
  - gulp build
  - gulp npmDist
deploy:
  - provider: pages
    local_dir: dist-site/
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: npm
    email: kim@shiftcph.dk
    api_key:
      secure: DFmBPTYFnUO61mmYputRy5NRfA0EbCqBwIZFlrMTEnfAJusB7Jd9RNclxZ+6XK30RyGA3HyfHjibZW+UKHMqRdT0BZd4W496cTqdG6bqrW/Vj95coUkM3k//YEDjVoG8b3CrKqYHjSe1TEyZRoCctf0T/BcV1ZIgfz0m3bSjoSMJuKe6nKGeqjhg4VMMOR4TgaeL+oVQPwWmW1RbsEZhmbVxBdBXS1p2sycAhc0CiTBfrRcdBV8VfPDyZfb+5k3lMYkFv0XMeNMzpS77U0XDcYJnamiFKlMRrXqd2mH3izBHb+OkDoeMVp4GdHTv9uWlZmRJAsREkQ+HLBxdary2ktkjSh7/U6XkAPkO6ksWKVTSc+iLIubOnZCDG3AbGaGa1C6TvhOJNpBlQwBX+6h+fYgjwmIex1hcsE47iT+2hi696gUnMsth6vk1Y6ZIVawrvB32SsFX3SjhP2CCyMaNiU7QSSLmzvRZWqwvqcMM/ve48g1LUzfMwij2iyJVJmTGgzlPkJFT4lL9slBIF2jA65B/AAyfZITh5WFWsWREyTtg2S4Rw/gGaLvg6CmhiyT8H23A7+9TO/huYsbgqkMbUeEt8VCfK7SyHJeJYcOROQpiatsWuvruZsUamwqkvE6R/3KxuU4/X839w1BsdPJBQetZPzO5o0ew0LTWyhBa9R4=
    on:
      tags: true
      all_branches: true
