language: node_js
node_js:
- '10'
script:
- gulp build
- gulp npmDist
deploy:
  matrix:
  - provider: pages
    local_dir: dist-site/
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    on:
      branch: master
  - provider: npm
    email: kim@shiftcph.dk
    on:
      tags: true
      all_branches: true
  api_key:
    secure: lF5+gitEJpo0kQrqp32L8RfzL7WIrR+uPFUm7I06fWy952RAosoy0LPCGp4VcxYko0SBf4IzKMe3/KaD4d17WVcjKTIgTwQ3GUhKLFH8xD8Pq0KGSMYNyZjp79cUz+iVOOhb7BKgLNya4iJe6aJWuaRwwOYXRfHW/AVGLzJG4OC8mn9SSkoh77v+NzjvPvtkAwQuf+VPeg+kD3L0i0edEcoZODa9TvZv1Fch3rjTguVj6jXOjcgEuDkL5s6DRu671+uGs+3yutmfzO344g3Y4ON0zz/87NL7xpdvfwWQRGfvmgw6+AEjkbYxHEcC5CKvkz1c8ZyZgH07B/ULGdrERYRLiFxNV9HPRWRVCIVVrlrff3Fm5pY2Qu0Cp5YGjUaPa1bRCgkMlCZfgS4BgWPNq8C7dBleZlJ5zpk+OSWeJx5dPO1qwis6X9eonzGeFWL+71bUIkeKJSKGlHZcHjKtOO8e5j5bX9QemLb0ZxP9fNwX7vO3LSZfm0zNGeyg6dzuweSNIPGBKVt0Woc3kZW3IWLsSEeMAzNWym1bOKy9431M0oOnzQMSP4/5SOCIJtE7texy5CYwC6NKVByYEJFMJ1sI5xyYBjlHelUB02vrfIeTLw7rpMWg2zTTNZAyaUPDfisAJbphF8ACe69wgdcI5GqLCCEkbIub/P614HeyJEk=
