language: node_js
node_js:
- '10'
script:
- gulp build
- gulp npmDist
deploy:
  matrix:
  - provider: pages
    local_dir: dist-site/
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    on:
      branch: master
  - provider: npm
    email: kim@shiftcph.dk
    skip_cleanup: true
    api_key:
      secure: QZPrJKWB8hBcDZSzttZO4ZIa1hUx3SMND9310Xl8MVSWxgJyP2wqoA9e5bd1XPe2ilZlp9egMwBnpJI+uN/6g3+kZeem7DE3S5qKSTd467vNdUEPfbnbntXn8Eq0wIOfpML9hIwLB7hRG6MvBJZ+hBiUtqKwON9pypnSPqqhbisS8oVsVn1vESr+le2eFRqMa42+M/96b3Evmdq5HXoM0napZU4pbWMDATGlQRg3cnoqTCr8aB6Jb9b9sbYTRDJ0hMDGbGg5DXWxsd7E9OC4rzQkkf70Ev4axxLClqQ8vuLgaNXGZh3BefaFjxDJFvsQnLMeZW9k5Qqy6OEg9js5cv6r97GIesdD61RpWt/9Q7GDNZYw4m2AuYHRcqIBdANl5HPOaqCDAUDMu6q9pEJDXl9Dx3Sj5ADY7kFcRa5Rbd82ajndL0zCNbRZAKptWx0m2PCCwJwfX/5g0VP14Ty1t5BoBzXD2/tchUrWQU0LXwq0WSStr6WnZ92pevMj5CxUCN2quE+/+sAWMDX1n/TL/vNY1H4TToQ8Bi7HRCamR1LeUv9p8SCb9AZl8yJSg7g3kOfM8SLtK3A9Wtr+UwUwwwrn8q6oJIdidDptflp78T1MkHBlmGHaArwLQGKBiC1fGGqYdgNmYA5bixzPYo5qihnurwJu6z/wi/MZuuFL2cE=
    on:
      tags: true
      all_branches: true
  api_key:
    secure: mqVvrieuuJLj9ix7gI9xDXCaVPUPLx/FfLBTlWqPWxTsS2twnkLipWbswxwv4eiLcldQFEMNzKoHCXjl2BftGKez5+OR3p7dm1Q8idOTiKJ63mzo7dPERljAQA1lWUdFZ3MAZnjrPGrj5FOgk+noASctNG4nNo1AJMpYvex099yZZkfw4PFjea6G6P07HtHo0XIK1ep5t2ZX+y9dQ1QO+ElF67U/on94LEuCU5PVJ2o8U5j0TOcfxe9ly2xdd+1diQi475RbadnMPUeyS7QM/MSYntILcDNZyzFoLLEi1pFMjsJqlQkBGvKd/t1jGrF4MrkeKS5kUre/PFHrToGiCIOnt5bKnmBqf11CM7tWlc5dWOi6BQXUSi03RGY9LZihtYE/UDIPZvS3jxtRavupgEvhuA0BCpcGMAnZ4G2589eza6QTQlQ8KpMNtJXoOrPOPuyG1h02x0Bs08hAAYo7D6q3rs4PCuUIvkH+9HMyzwmPj1ZDpbzGCT42DZaxjipWPWDtS3mpfUowBjxnX6h7FulMtSGSG7p/piQGPcX0xo4yEGR//FUxrtHnVvQw16OlOavzI87rIPYBo127KDBR3AsZUpKmnZRrNQu01Ztz8OcHozrE28jCFk+FFJpHVsoMXa0GzvxXVqQ+lha+3/k+FbR0v3AmJKuJDplbMClMUFY=
