language: node_js
node_js:
- '10'
script:
- npm run build
- npm run build:npm
before_deploy:
- cd dist-npm
deploy:
  - provider: pages
    local_dir: dist-site/
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    on:
      branch: master
  - provider: npm
    email: kim@shiftcph.dk
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on:
      tags: true
      repo: youseedk/dna
      all_branches: true
notifications:
  email:
    on_success: never
    on_failure: always
